### ISSUE TITLE
JSON formatting inconsistency?

### ISSUE THREAD

**Issue by jmcx** [triggermesh/tmctl#108]
I'm wondering if there is an issue hiding here somewhere.

### Case 1
`tmctl send-event {"hello":"world"}`

shows up in `watch` as:

`"{hello:world}"`

### Case 2
`tmctl send-event '{"hello":"world"}'` (added single quotes)

shows up in `watch`as:

`"{\"hello\":\"world\"}"`

### Case 3
and if I `curl http://localhost:59936 -H 'Content-type: application/json' -d '{"hello":"world"}'` to a webhook source it shows in `watch`as:

```
{
    "hello": "world"
}
```

Any thoughts? cc @odacremolbap

**Comment by tzununbekov** [comment]
`send-event` behavior was reviewed, and a couple of data formatting fixes were added.
Command checks if input data is valid JSON and if it is, sets the `datacontenttype` to `application/json`, otherwise to`text/plain`. 
Formatting expectations are the same as in Curl requests: `"foo"` in the command line is equivalent to `foo` which is not a JSON string, `'"foo"'` is a JSON string, etc. JSON objects formatting has the same logic - `'{...}'` should be used to preserve the data format, otherwise it will be sent as plain text.
Please review and comment if needed.

**Comment by jmcx** [comment]
Sounds good, FYI I tentatively added the phrase:

"Formatting expectations are the same as in Curl requests: "foo" in the command line is equivalent to foo which is not a JSON string, '"foo"' is a JSON string, etc. JSON objects formatting has the same logic - '{...}' should be used to preserve the data format, otherwise it will be sent as plain text."

to the CLI commands reference in the docs, under send-event.
